apiVersion: v2

description: A Helm chart for Singularity Registry

name: sregistry
type: application

version: 0.1.1
appVersion: 1.1.27

home: https://singularityhub.github.io/

sources:
- https://github.com/singularityhub/sregistry

dependencies:

- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.4.2
  condition: postgresql.enabled
  tags:
  - postgres
  - database

- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.10.1
  condition: redis.enabled
  tags:
  - redis
  - cache
 
- name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.3
  condition: minio.enabled
  tags:
  - minio
  - storage
