{{- if .Values.images.nginx.ingress -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.images.nginx.ingressClass | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.images.nginx.maxBodySize | quote }}
    nginx.ingress.kubernetes.io/client-body-buffer-size: {{ .Values.images.nginx.bodyBufferSize | quote }}
spec:
  {{- if .Values.images.nginx.tlsSecretName }}
  tls:
  - secretName: {{ .Values.images.nginx.tlsSecretName | quote }}
    hosts:
    - {{ .Values.config.domainName | quote }}
  {{- end }}
  rules:
  - host: {{ .Values.config.domainName | quote }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: nginx
            port:
              number: {{ .Values.images.nginx.port }}
        pathType: Prefix
{{- end }}
